exceptionn = input('ВВедите значения', )
result = eval(str(exceptionn))
print(result)